version: 0.2


phases:
  install:
    commands:
      - echo Entered the install phase...
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - bundle
  build:
    commands:
      - echo Entered the build phase...
      - rspec -o test_results.json -f json
  post_build:
    commands:
      - echo Entered the post_build phase...

artifacts:
  files:
    - test_results.json
