version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "aws_pipeline"
    IMAGE_TAG: "latest"
    AWS_ACCOUNT_ID: 799634677741
    AWS_DEFAULT_REGION: us-east-1


phases:
  install:
    commands:
      - echo Entered the install phase...
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - bundle
  build:
    commands:
      - echo Entered the build phase...
      - rspec -o test_results.json -f json
      - echo Building Container
      - echo $IMAGE_REPO_NAME
      - echo $IMAGE_TAG
      - echo $AWS_ACCOUNT_ID
      - echo $AWS_DEFAULT_REGION
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Entered the post_build phase...

artifacts:
  files:
    - test_results.json
