version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - bundle
  build:
    commands:
      - echo Entered the build phase...
      - rspec -o test_results.json -f json
  post_build:
    commands:
      - echo Entered the post_build phase...

artifacts:
  files:
    - test_results.json
